name: zaptools_server
description: A toolkit for Event-Driven websocket management.
version: 0.1.0
repository: https://github.com/NathanDraco22/zaptools-dart
topics:
  - server
  - websocket

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  uuid: ^4.1.0
  web_socket_channel: ^2.4.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
