name: zaptools_server
description: A toolkit for Event-Driven websocket management.
version: 0.3.0
repository: https://github.com/NathanDraco22/zaptools-dart
topics:
  - server
  - websocket

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  uuid: ^4.1.0
  web_socket_channel: ^2.4.5

dev_dependencies:
  alfred: ^1.1.1
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.4.6
  mockito: ^5.4.2


screenshots:
  - description: The zaptools logo
    path: screenshots/zaptools-logo.png