name: zaptools
description: A toolkit for Event-Driven websocket management.
version: 0.1.0
repository: https://github.com/NathanDraco22/zaptools-dart
publish_to: none
topics:
  - server
  - websocket
  - client

environment:
  sdk: ^3.0.0


dependencies:
  uuid: ^4.1.0
  web_socket_channel: ^2.4.0
  zaptools_client:
    path: packages/zaptools_client
  zaptools_server:
    path: packages/zaptools_server

dev_dependencies:
  alfred: ^1.1.1
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.4.6
  mockito: ^5.4.2

